-- Run this once in your Supabase SQL editor.
create table if not exists public.halloween_polaroids (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text,
  visitor_id text not null,
  created_at timestamptz not null default now()
);

alter table public.halloween_polaroids enable row level security;

drop policy if exists "Anyone can view Halloween photos" on public.halloween_polaroids;
create policy "Anyone can view Halloween photos"
on public.halloween_polaroids for select to anon, authenticated using (true);

drop policy if exists "Anyone can post Halloween photos" on public.halloween_polaroids;
create policy "Anyone can post Halloween photos"
on public.halloween_polaroids for insert to anon, authenticated
with check (char_length(caption) <= 40 and char_length(visitor_id) <= 100);

-- Create a public bucket named exactly: HalloweenPolaroids
-- Then add Storage policies in the Storage dashboard allowing public uploads
-- and public reads for this bucket.
