-- Run this once in your Supabase SQL editor.

create table if not exists public.halloween_polaroids (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text,
  visitor_id text not null,
  created_at timestamptz not null default now()
);

alter table public.halloween_polaroids enable row level security;

drop policy if exists "Anyone can view Halloween photos" on public.halloween_polaroids;
create policy "Anyone can view Halloween photos"
on public.halloween_polaroids for select to anon, authenticated using (true);

drop policy if exists "Anyone can post Halloween photos" on public.halloween_polaroids;
create policy "Anyone can post Halloween photos"
on public.halloween_polaroids for insert to anon, authenticated
with check (char_length(coalesce(caption,'')) <= 40 and char_length(visitor_id) between 1 and 100);

-- Realtime feed
do $$
begin
  alter publication supabase_realtime add table public.halloween_polaroids;
exception when duplicate_object then
  null;
end $$;

-- IMPORTANT: Create a PUBLIC Storage bucket named exactly HalloweenPolaroids
-- in Supabase Storage, then run the storage policies below.

drop policy if exists "Halloween public reads" on storage.objects;
create policy "Halloween public reads"
on storage.objects for select to anon, authenticated
using (bucket_id = 'HalloweenPolaroids');

drop policy if exists "Halloween public uploads" on storage.objects;
create policy "Halloween public uploads"
on storage.objects for insert to anon, authenticated
with check (bucket_id = 'HalloweenPolaroids');
